[workspace]
authors = [
    "avanmalleghem <antoine.vanmalleghem@botronics.be>",
    "csimon-be <christophe.simon@botronics.be",
    "davidmoli-botronics <david.moli@botronics.be>",
    "EnzoGhisoni <enzo.ghisoni@botronics.be",
    "Nicodaube <nicolas.daube@botronics.be>"    
]
channels = ["robostack-kilted", "conda-forge"]
name = "RustyRover"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[activation]
scripts = [
    "../rclrs_install_ws/install/setup.sh",
    "install/setup.sh"    
]

[activation.env]
DBUS_SYSTEM_BUS_ADDRESS = "unix:path=/var/run/dbus/system_bus_socket" # Needed to access the dbus for ble

[tasks]
build = "colcon build --symlink-install"
clean = "rm -rf build/ install/ log/"
source = "source install/setup.bash"
rviz = "rviz2 -d /src/rusty_rviz/config/rusty_realtime.rviz"
start = "ros2 launch rusty_bringup bringup.launch.py sim_mode:=false"

[dependencies]
ros-kilted-desktop = ">=0.12.0,<0.13"
ros-kilted-ros-gz = ">=2.1.9,<3"
ros-kilted-xacro = "*"
ros-kilted-joint-state-publisher = ">=2.4.0,<3"
ros-kilted-joint-state-publisher-gui = ">=2.4.0,<3"
ros-kilted-gz-ros2-control = ">=2.0.9,<3"
ros-kilted-ros2-control = ">=5.2.0,<6"
ros-kilted-ros2-controllers = ">=5.2.0,<6"
ros-kilted-controller-manager = ">=5.2.0,<6"
ros-kilted-gz-ros2-control-demos = ">=2.0.9,<3"
ros-kilted-cv-bridge = ">=4.1.0,<5"
ros-kilted-image-transport = ">=6.1.2,<7"
ros-kilted-v4l2-camera = ">=0.7.1,<0.8"


[pypi-dependencies]
colcon-cargo = { git = "https://github.com/colcon/colcon-cargo.git" }
colcon-ros-cargo = { git = "https://github.com/colcon/colcon-ros-cargo.git" }
