[workspace]
authors = [
    "avanmalleghem <antoine.vanmalleghem@botronics.be>",
    "csimon-be <christophe.simon@botronics.be",
    "davidmoli-botronics <david.moli@botronics.be>",
    "EnzoGhisoni <enzo.ghisoni@botronics.be",
    "Nicodaube <nicolas.daube@botronics.be>"    
]
channels = ["robostack-kilted", "conda-forge"]
name = "RustyRover"
platforms = ["linux-64"]
version = "0.1.0"

[activation]
scripts = [
    "../rclrs_install_ws/install/setup.bash",
    "install/setup.sh"    
]

[tasks]
build = "colcon build --symlink-install"
clean = "rm -rf build/ install/ log/"
source = "source install/setup.bash"
rviz = "rviz2 -d src/rusty_description/rviz/rusty_realtime.rviz"

[dependencies]
ros-kilted-desktop = ">=0.12.0,<0.13"
ros-kilted-ros-gz = ">=2.1.9,<3"
ros-kilted-xacro = "*"
ros-kilted-joint-state-publisher = ">=2.4.0,<3"
ros-kilted-joint-state-publisher-gui = ">=2.4.0,<3"
ros-kilted-gz-ros2-control = ">=2.0.9,<3"
python = ">=3.12.12,<3.13"
compilers = ">=1.11.0,<2"
ffmpeg = "<8"
ros-kilted-ros2-control = ">=5.2.0,<6"
ros-kilted-ros2-controllers = ">=5.2.0,<6"
filelock = ">=3.20.3,<4"
ros-kilted-controller-manager = ">=5.2.0,<6"
ros-kilted-gz-ros2-control-demos = ">=2.0.9,<3"




