controller_manager:
  ros__parameters:
    update_rate: 50

    use_sim_time: False 

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: False

# Configuration for the Differential Drive Controller
diff_cont:
  ros__parameters:
    use_sim_time: False
    
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    
    wheel_separation: 0.10
    wheel_radius: 0.033

    use_stamped_vel: true 

    position_feedback: false 
    open_loop: true

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.0
        max_acceleration: 1.0
        max_deceleration: -10.0
        max_acceleration_reverse: -1.0
        max_deceleration_reverse: 10.0

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.14
        max_acceleration: 1.0
        max_deceleration: -1.0