controller_manager:
  ros__parameters:
    update_rate: 100
    # In simulation, the Gazebo plugin overrides this to True
    use_sim_time: False 

    # Declaration of controllers
    diff_cont:
      type: diff_drive_controller/DiffDriveController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Configuration for the Joint State Broadcaster
joint_state_broadcaster:
  ros__parameters:
    use_sim_time: False

# Configuration for the Differential Drive Controller
diff_cont:
  ros__parameters:
    use_sim_time: False
    
    # Frame IDs
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true

    # Joint Names (must match URDF)
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    
    # Kinematics
    wheel_separation: 0.105
    wheel_radius: 0.03

    # Command interface
    use_stamped_vel: true 

    # --- NO-ENCODER SETTINGS (Open Loop) ---
    position_feedback: false 
    open_loop: true
    # ----------------------------------------

    # Velocity Limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.0
        max_acceleration: 1.0
        max_deceleration: -10.0
        max_acceleration_reverse: -1.0
        max_deceleration_reverse: 10.0

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.14
        max_acceleration: 1.0
        max_deceleration: -1.0