[workspace]
authors = [
    "avanmalleghem <antoine.vanmalleghem@botronics.be>",
    "csimon-be <christophe.simon@botronics.be",
    "davidmoli-botronics <david.moli@botronics.be>",
    "EnzoGhisoni <enzo.ghisoni@botronics.be",
    "Nicodaube <nicolas.daube@botronics.be>"    
]
channels = ["robostack-kilted", "conda-forge"]
name = "rclrs_install_ws"
platforms = ["linux-64"]
version = "0.1.0"

[activation]
scripts = ["install/setup.sh"]

[tasks]
build = "colcon build --packages-up-to examples_rclrs_minimal_pub_sub"
clean = "rm -rf build/ install/ log/ .cargo/"

[dependencies]
ros-kilted-desktop = ">=0.12.0,<0.13"
colcon-common-extensions = ">=0.3.0,<0.4"
rust-src = ">=1.92.0,<2"
setuptools = ">=80.9.0,<81"
rust = ">=1.92.0,<1.93"
vcstool = ">=0.3.0,<0.4"
python = ">=3.12.12,<3.13"


[pypi-dependencies]
colcon-cargo = { git = "https://github.com/colcon/colcon-cargo.git" }
colcon-ros-cargo = { git = "https://github.com/colcon/colcon-ros-cargo.git" }
